### ISSUE TITLE
Unsichtbare Wiggles

### ISSUE THREAD

**Issue by cech12** [DigglesMods/BugFix#14]
Manchmal kommt es vor, dass ein Wiggle unsichbar ist und nur noch sein Hut zu sehen ist. Der Zwerg ist dann auch nicht mehr auswählbar und auch nicht mehr in der Liste der Zwerge zu finden.
Eine Vermutung ist, dass das mit dem Bordell zu tun hat, da bei einem Besuch dort, kurzzeitig der Zwerg vollständig verschwindet. Ein weiterer Besuch eines unsichtbaren Zwerges im Bordell macht ihn wieder sichbar.

**Comment by saibantes** [comment]
Die Vermutung ist korrekt: Der Fehler tritt genau dann auf, wenn die Freizeit des Bordellbesuchers endet, während er gerade ... bedient wird, Man kann das absichtlich reproduzieren, wenn man die Arbeitszeiteinteilung ändert, während er gerade unsichtbar ist.

Vorschlag für den Bugfix: In bordell.tcl, ersetze
if {$progress==4} {
durch
if {($progress>=4) && !$finished} {

**Comment by cech12** [comment]
Sehr gut, dann kann man das Verhalten ja gut reproduzieren und eine mögliche Lösung gibts auch schon! :D Wenn ich Zeit habe, schaue ich mir das mal an und fixe es :)
