### ISSUE TITLE
Cut tree vs get from storage

### ISSUE THREAD

**Issue by cech12** [DigglesMods/BugFix#16]
reji:
Also not sure it's bug out supposed, but gnomes mainly go to cut trees for mushroom's hats/stems instead of picking them from storage (i have like dozen). Probably priority thing - give will not use storage, if he can cut new tree?

**Comment by saibantes** [comment]
The work-time planning is all done in compiled code, not the Tcl scripts. Therefore I don't see a way to change this - unless you replace the work scheduler completely, which is what the RevisedPlanner mod does.

In RevsedPlanner, gnomes prefer material that is closer to the manufacturing site (there is no difference between storage and stuff just laying around). Cutting down a tree/mushroom is equivalent to walking another 50 units of distance (currently line 337 in prod_autoprod.tcl).

**Comment by cech12** [comment]
Thanks for your answer! I think, this issue is not really an issue and the searched behaviour could be achieved by using the Revised Planner mod :)
