### ISSUE TITLE
energy consumption of gym and hospital

### ISSUE THREAD

**Issue by saibantes** [DigglesMods/BugFix#19]
If you select a gym or hospital, the ranges of all power plants are shown (blue shaded circles). This is because in those classes, "set_energyconsumption this 2" is called, even though no energy class is defined.
Is this worth fixing (-> "set_energyconsumption this **0**")?

**Comment by cech12** [comment]
According to the (German) solution book, the two buildings have no energy requirements. That's why it makes sense to fix it :)
