### ISSUE TITLE
Schmiede Hamster warning

### ISSUE THREAD

**Issue by cech12** [DigglesMods/BugFix#7]
schmiede.tcl: no prod_actions method for Hamster (calling prod_actions_default)

**Comment by Aehrraid** [comment]
Can you explain why that's a problem?

**Comment by cech12** [comment]
Sorry for the few information ^^ I added this issue as a reminder. During some tests I saw this message in the logs. I wanted to look into the code to find some bugs :)

**Comment by cech12** [comment]
fixed here: https://github.com/DigglesMods/BugFix/commit/475e5da9a65f396b9c08de71d4ffb09fb5f9b4df
